export default [
  // --- Books (Academic & Non-Academic) ---
  {
    name: "Physics Textbook Part 1 for Class 12",
    price: 500,
    description:
      "A comprehensive physics textbook for Class 12 Science stream students.",
    category: "Book",
    subCategory: "Academic",
    academicCategory: "Science",
    class: "Class 12",
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://m.media-amazon.com/images/I/41Y5QZ4H1XL._SX342_SY445_.jpg",
    ],
  },
  {
    name: "Nepali Grammar Book for Class 10",
    price: 350,
    description: "Detailed grammar reference for Class 10 Nepali subject.",
    category: "Book",
    subCategory: "Academic",
    academicCategory: "Arts",
    class: "Class 10",
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://anyflip.com/ilkfk/anhw/files/shot.jpg"],
  },
  {
    name: "Mathematics Textbook for Class 11",
    price: 480,
    description:
      "Standard mathematics textbook aligned with national curriculum.",
    category: "Book",
    subCategory: "Academic",
    academicCategory: "Science",
    class: "Class 11",
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://m.media-amazon.com/images/I/41Y5QZ4H1XL._SX342_SY445_.jpg",
    ],
  },
  {
    name: "The Complete Novels of Sherlock Holmes",
    price: 700,
    description:
      "A classic detective fiction collection by Sir Arthur Conan Doyle.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://m.media-amazon.com/images/I/51r6KXk3GEL._SX331_BO1,204,203,200_.jpg",
    ],
  },
  {
    name: "Harry Potter and the Philosopher's Stone",
    price: 600,
    description:
      "Fantasy novel by J.K. Rowling, first in the Harry Potter series.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://www.harrypotterfanzone.com/wp-content/uploads/2010/12/uk-philosophers-stone-2010.jpg",
    ],
  },
  {
    name: "The Diary of a Young Girl",
    price: 400,
    description:
      "Autobiographical diary by Anne Frank, a World War II classic.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/51Z0nLAfLmL._SX324_BO1,204,203,200_.jpg",
    ],
  },
  {
    name: "To Kill a Mockingbird",
    price: 450,
    description:
      "Harper Lee's Pulitzer Prize-winning novel of racial injustice.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81Otwki3r-L.jpg",
    ],
  },
  {
    name: "The Great Gatsby",
    price: 420,
    description: "F. Scott Fitzgerald's classic novel of the Jazz Age.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81af+MCATTL.jpg",
    ],
  },
  {
    name: "Sapiens: A Brief History of Humankind",
    price: 800,
    description:
      "Yuval Noah Harari's bestselling exploration of human history.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/713jIoMO3UL.jpg",
    ],
  },
  {
    name: "Rich Dad Poor Dad",
    price: 350,
    description: "Robert Kiyosaki's classic on personal finance and investing.",
    category: "Book",
    subCategory: "Non-Academic",
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
    ],
  },

  // --- Sport ---
  {
    name: "Football",
    price: 1200,
    description:
      "High-quality size 5 football suitable for all weather conditions.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://media.istockphoto.com/id/1270653477/photo/soccer-ball-on-green-grass.jpg",
    ],
  },
  {
    name: "Cricket Bat",
    price: 1500,
    description: "Grade 1 Kashmir Willow bat for professional matches.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://m.media-amazon.com/images/I/71z2+6GJvSL._AC_SL1500_.jpg"],
  },
  {
    name: "Badminton Racket Set",
    price: 950,
    description: "Pair of lightweight badminton rackets with a carrying case.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://m.media-amazon.com/images/I/71z2+6GJvSL._AC_SL1500_.jpg"],
  },
  {
    name: "Basketball",
    price: 1100,
    description: "Durable outdoor/indoor basketball.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81w+3k4U5GL._AC_SL1500_.jpg",
    ],
  },
  {
    name: "Tennis Racket",
    price: 1300,
    description: "Lightweight tennis racket for beginners and pros.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L._AC_SL1500_.jpg",
    ],
  },
  {
    name: "Table Tennis Bat",
    price: 400,
    description: "Professional table tennis bat with high grip.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71w2yQw8QnL._AC_SL1500_.jpg",
    ],
  },
  {
    name: "Skipping Rope",
    price: 150,
    description: "Adjustable skipping rope for fitness and training.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/61wQw8QnL._AC_SL1500_.jpg",
    ],
  },
  {
    name: "Volleyball",
    price: 900,
    description: "Official size and weight volleyball.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/81w+3k4U5GL._AC_SL1500_.jpg",
    ],
  },
  {
    name: "Hockey Stick",
    price: 800,
    description: "Sturdy hockey stick for field hockey.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71QKQ9mwV7L._AC_SL1500_.jpg",
    ],
  },
  {
    name: "Shuttlecock Pack",
    price: 200,
    description: "Pack of 6 feather shuttlecocks for badminton.",
    category: "Sport",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: [
      "https://images-na.ssl-images-amazon.com/images/I/71w2yQw8QnL._AC_SL1500_.jpg",
    ],
  },

  // --- Gift ---
  {
    name: "Birthday Greeting Card",
    price: 100,
    description:
      "Beautifully designed card with envelope, perfect for birthdays.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1607746882042-944635dfe10e"],
  },
  {
    name: "Gift Mug - World's Best Mom",
    price: 350,
    description: "Printed ceramic mug ideal for Mother’s Day or birthdays.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1585155774677-1a1b5f1c1f1c"],
  },
  {
    name: "Mini Photo Frame",
    price: 280,
    description: "Small wooden frame suitable for desk decoration or gifting.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519681393784-d120267933ba"],
  },
  {
    name: "Personalized Keychain",
    price: 120,
    description: "Customizable keychain with your name or message.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519125323398-675f0ddb6308"],
  },
  {
    name: "Wooden Jewelry Box",
    price: 450,
    description: "Handcrafted jewelry box with intricate design.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb"],
  },
  {
    name: "Scented Candle Set",
    price: 300,
    description: "Set of 3 scented candles for relaxation.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1464983953574-0892a716854b"],
  },
  {
    name: "Desk Organizer",
    price: 250,
    description: "Wooden desk organizer for office or study table.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1515378791036-0648a3ef77b2"],
  },
  {
    name: "Travel Diary",
    price: 200,
    description: "Leather-bound diary for travel memories.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1465101046530-73398c7f28ca"],
  },
  {
    name: "Wall Art Poster",
    price: 180,
    description: "Inspirational quote wall art for home decor.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb"],
  },
  {
    name: "Handmade Soap Set",
    price: 220,
    description: "Natural handmade soaps in assorted fragrances.",
    category: "Gift",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519125323398-675f0ddb6308"],
  },

  // --- Stationery ---
  {
    name: "A4 Notebook - 200 Pages",
    price: 90,
    description: "Hardcover notebook with ruled pages, ideal for students.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1588776814546-ec7d9c1d1c1c"],
  },
  {
    name: "Ballpoint Pen Set (Pack of 10)",
    price: 150,
    description: "Smooth writing pens in blue and black ink.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1588776814546-ec7d9c1d1c1c"],
  },
  {
    name: "Scientific Calculator - Casio fx-991ES Plus",
    price: 2200,
    description: "Advanced scientific calculator with 417 functions.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://m.media-amazon.com/images/I/71z2+6GJvSL._AC_SL1500_.jpg"],
  },
  {
    name: "Stapler Machine",
    price: 180,
    description: "Compact stapler for office and school use.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1515378791036-0648a3ef77b2"],
  },
  {
    name: "Highlighter Pen Set",
    price: 120,
    description: "Pack of 5 assorted color highlighters.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1465101046530-73398c7f28ca"],
  },
  {
    name: "Sticky Notes (Pack of 12)",
    price: 80,
    description: "Colorful sticky notes for reminders and bookmarks.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1464983953574-0892a716854b"],
  },
  {
    name: "Drawing Book",
    price: 100,
    description: "A4 size drawing book for art and sketches.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1506744038136-46273834b3fb"],
  },
  {
    name: "Geometry Box",
    price: 200,
    description: "Complete geometry box with compass, scale, and protractor.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519125323398-675f0ddb6308"],
  },
  {
    name: "Eraser Pack",
    price: 40,
    description: "Pack of 5 dust-free erasers.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519681393784-d120267933ba"],
  },
  {
    name: "Whiteboard Marker Set",
    price: 160,
    description: "Set of 4 whiteboard markers in assorted colors.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1585155774677-1a1b5f1c1f1c"],
  },
  {
    name: "Desk Calendar 2025",
    price: 130,
    description: "Spiral-bound desk calendar for the year 2025.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1465101046530-73398c7f28ca"],
  },
  {
    name: "Binder Clips (Pack of 20)",
    price: 70,
    description: "Durable binder clips for organizing documents.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1464983953574-0892a716854b"],
  },
  {
    name: "Correction Pen",
    price: 60,
    description: "Quick-dry correction pen for clean corrections.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1515378791036-0648a3ef77b2"],
  },
  {
    name: "Plastic Ruler 30cm",
    price: 30,
    description: "Transparent plastic ruler for precise measurements.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519681393784-d120267933ba"],
  },
  {
    name: "File Folder (Set of 5)",
    price: 110,
    description: "Colorful file folders for document organization.",
    category: "Stationery",
    subCategory: null,
    academicCategory: null,
    class: null,
    user: "68418a9e4ad8ab16bf4cc3b2",
    images: ["https://images.unsplash.com/photo-1519125323398-675f0ddb6308"],
  },
];
